package payroll_processing_system.application;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import java.io.IOException;

/**
 * Main class extends javafx application class and connects the model, view and controller 
 */
public class Main extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    /**
     * starts JavaFX application with stage generated by JavaFX runtime
     */
    public void start(Stage stage) throws Exception {
        Stage window = stage;
        Parent root;
        try {
             root = FXMLLoader.load(getClass().getResource("../view/home.fxml"));
             window.setTitle("Payroll Processing");
             window.setScene(new Scene(root, 1300, 600));
             window.show();
        }
        catch (IOException e) {
            System.out.println(IoFields.LOADING_ERROR);
        }
    }
}
